platform :osx, '12'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
require_relative '../scripts/anime4k_media_kit_patch'
require_relative '../scripts/anime4k_mpv_pacing_patch'
require_relative '../scripts/anime4k_metal_capi_install'

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

pre_install do |_installer|
  anime4k_plugin_root = anime4k_flutter_plugin_root(
    project_dir: __dir__,
    platform: :macos
  )
  anime4k_native_dir = File.expand_path('../native/anime4k_metal', __dir__)
  patch_anime4k_media_kit_video(
    plugin_root: anime4k_plugin_root,
    native_dir: anime4k_native_dir,
    platform: :macos
  )
  patch_anime4k_mpv_render_pacing(
    plugin_root: anime4k_plugin_root,
    platform: :macos
  )
  install_anime4k_metal_capi(
    plugin_root: anime4k_plugin_root,
    native_dir: anime4k_native_dir,
    platform: :macos
  )
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '12.0'
    end
    flutter_additional_macos_build_settings(target)
    retain_anime4k_metal_capi_symbols(target)
  end
end